config/routes.rb
QnA::Application.routes.draw do
  resources :answers do
    member do
      post 'vote'
    end
  end

  resources :questions

  devise_for :users
  
  match 'pages/questions' => 'pages#questions'

  root :to => 'pages#home'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, :counter_cache => true
  
  default_scope :include => :user
  
  attr_accessible :body
  
  has_reputation :votes, :source => :user, :aggregated_by => :sum
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, :dependent => :destroy
  #default_scope :include => :answers
  
  attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :questions, :dependent => :destroy
  has_many :answers
  
  has_many :evaluations, :class_name => "RSEvaluation", :as => :source

  has_reputation :votes, :source => {:reputation => :votes, :of => :answers}, :aggregated_by => :sum

  def voted_for?(answer)
    evaluations.where(target_type: answer.class, target_id: haiku.id).present?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user! #, :except => [:home]
  
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new
    @answer.user_id = current_user.id.to_i
    @answer.question_id = params[:answer][:question_id].to_i
    @answer.body = params[:answer][:body]

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
  
  def vote
    value = params[:type] == "up" ? 1 : -1
    @answer = Answer.find(params[:id])
    
    @ans_voted = false
    if @answer.user != current_user
      @answer.add_or_update_evaluation(:votes, value, current_user)
      @vc = @answer.reputation_value_for(:votes).to_i
      @alert = "Thank you for voting"
      @ans_voted = true
    else
      @alert = "Can not vote on own answer"
    end

    respond_to do |format|
      format.html { redirect_to :back, notice: @alert }
      format.js
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:home]
  
  def home
    @questions = Question.order("created_at DESC").page(params[:page]).per(10)
    
    #@latest_answered_qid = Answer.select("DISTINCT(question_id)").last(5).reverse
    #@latest_answered_q = Question.find(:all, :conditions => "id in (#{@latest_answered_qid})")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
      format.rss
    end
  end
  
  def questions
    @questions = Question.order("created_at DESC").includes(:user).where(:user_id => current_user.id).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
      format.rss
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.includes(:user, :answers).order("created_at DESC")

    respond_to do |format|
      #format.html # index.html.erb
      #format.json { render json: @questions }
      format.rss
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id], :include => :answers)
    @answers = @question.answers.find_with_reputation(:votes, :all, order: "votes desc")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to pages_questions_path }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<% @answer = Answer.new if @answer.blank? %>
<%= form_for @answer, :html => { :class => "form-horizontal new_answer" } do |f| %>
	<% if @answer.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
			<ul>
				<% @answer.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.hidden_field :question_id, :value => @question.id %>
	<fieldset>
		<div class="control-group">
			<%= f.text_area :body, :placeholder => "Add answer", :class => "input-xxlarge qna-ta-a" %>
		</div>
		<%= f.submit "Add", :class => "btn" %>
	</fieldset>
<% end %>

app/views/answers/_new.html.erb
<div class="page-header">
	<h5>Add answer</h5>
</div>
<%= render 'form' %>

app/views/answers/create.js.erb
var new_elem = $("<%= escape_javascript(render :partial => 'questions/answer', :locals => { :answer => @answer }) %>").hide();
$("div.qna-q-a").append(new_elem);
new_elem.slideDown("slow");

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>User</th>
    <th>Question</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.user %></td>
    <td><%= answer.question %></td>
    <td><%= answer.body %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @answer.user %>
</p>

<p>
  <b>Question:</b>
  <%= @answer.question %>
</p>

<p>
  <b>Body:</b>
  <%= @answer.body %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/answers/vote.js.erb
<% if @ans_voted %>
	$(".alert").removeClass("alert-error").addClass("alert-info").html("<%= @alert %>").slideDown("slow");
	$("#avc-<%= @answer.id %>").html("<%= @vc %>")
<% else %>
	$(".alert").removeClass("alert-info").addClass("alert-error").html("<%= @alert %>").slideDown("slow");
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<%= link_to "QnA", root_path, :class => "brand" %>
			<ul class="nav pull-right">
				<li class="divider-vertical"></li>
				<li>
					<% if user_signed_in? %>
						<div class="btn-group">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-user"></i> <%= current_user.email %>
								(<%= current_user.reputation_value_for(:votes).to_i %>)
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", "#" %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", destroy_user_session_path %></li>
							</ul>
						</div>
					<% else %>
						<%= link_to "Login", "#" %>
					<% end %>
				</li>
			</ul>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="divider-vertical"></li>
					<li><%= link_to "My questions", pages_questions_path %></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>QnA</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= yield :head %>
</head>
<body>
	<%= render :partial => "layouts/header" %>
	<div class="container">
		<p class="alert"></p>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_question.html.erb
<div class="row">
	<div class="span9 qna-que">
		<div class="row">
			<div class="span1 qna-que-cnt">
				<div>
					<%= question.answers.size %>
				</div>
				<div>
					<% if question.answers.size > 1 %>
						answers
					<% else %>
						answer
					<% end %>
				</div>
			</div>
			<div class="span8">
				<%= link_to content_tag(:h4, question.body), question, :class => "qna-que-link" %>
				<div class="when">
					<h6><small><%= time_ago_in_words(question.created_at) %> - by <%= mail_to question.user.email %></small></h6>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<% content_for :head, auto_discovery_link_tag(:rss, questions_url(:format => "rss")) %>
<% if !user_signed_in? %>
	<div class="hero-unit">
		<h1>QnA</h1>
		<%= link_to "Sign in", new_user_session_path %>
		or
		<%= link_to "Sign up", new_user_registration_path, :style => "color:#F89406;" %>
	</div>
<% else %>
	<div class="page-header">
		<h1>
			Questions
			<%= link_to "Ask question", new_question_path, :class => "btn btn-primary pull-right" %>
		</h1>
	</div>
	<div class="row">
		<div class="span9">
			<% if @questions.blank? %>
				<h3>All questions will be listed here.</h3>
			<% else %>
				<%= render :partial => "pages/question", :collection => @questions %>
				<div><%= paginate @questions %></div>
			<% end %>
		</div>
		<div class="span3">
			<div class="well sidebar-nav">
				<ul class="nav nav-list">
					<li class="nav-header">All QnA rss</li>
					<li><%= link_to image_tag("feed-icon-28x28.png")+content_tag(:span, ' All QnA', :style => "vertical-align:middle;"), questions_url(:format => "rss") %></li>
				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/pages/questions.html.erb
<% content_for :head, auto_discovery_link_tag(:rss, questions_url(:format => "rss")) %>
<div class="page-header">
	<h1>
		Questions
		<%= link_to "Ask question", new_question_path, :class => "btn btn-primary pull-right" %>
	</h1>
</div>
<div class="row">
	<div class="span9">
		<% if @questions.blank? %>
			<h3>Your questions will be listed here.</h3>
		<% else %>
			<%= render :partial => "pages/question", :collection => @questions %>
			<div><%= paginate @questions %></div>
		<% end %>
	</div>
	<div class="span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<li class="nav-header">My QnA rss</li>
				<li><%= link_to image_tag("feed-icon-28x28.png")+content_tag(:span, ' My questions rss', :style => "vertical-align:middle;"), questions_url(:format => "rss") %></li>
			</ul>
		</div>
	</div>
</div>

app/views/questions/_answer.html.erb
<div>
	<hr/>
	<div class="row">
		<div class="span1 vote-section">
			<div class="vote-control">
				<%= link_to content_tag(:i, '', :class => "icon-chevron-up"), vote_answer_path(answer, type: "up"), :class => "vote-ans" %>
			</div>
			<div id="avc-<%= answer.id %>" class="vote-control vote-count">
				<%= answer.reputation_value_for(:votes).to_i %>
			</div>
			<div class="vote-control">
				<%= link_to content_tag(:i, '', :class => "icon-chevron-down"), vote_answer_path(answer, type: "down"), :class => "vote-ans" %>
			</div>
		</div>
		<div class="span8 qna-q-a-d">
			<%= answer.body %>
		</div>
	</div>
</div>

app/views/questions/_answerer.html.erb
<li><%= mail_to answerer.user.email %></li>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => "form-horizontal" } do |f| %>
	<% if @question.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

			<ul>
				<% @question.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<fieldset>
		<div class="control-group">
			<%= f.label :title, :class => "control-label" %>
			<div class="controls"><%= f.text_field :title, :class => "input-xxlarge" %></div>
		</div>
		<div class="control-group">
			<%= f.label :body, :class => "control-label" %>
			<div class="controls"><%= f.text_area :body, :class => "input-xxlarge qna-ta-q" %></div>
		</div>
		<div class="form-actions">
			<%= f.submit "Submit", :class => "btn btn-primary" %>
		</div>
	</fieldset>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.user %></td>
    <td><%= question.title %></td>
    <td><%= question.body %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<div class="page-header">
	<h1>New question</h1>
</div>
<%= render 'form' %>

app/views/questions/show.html.erb
<div class="row">
	<div class="span9">
		<div class="page-header">
			<h3><%= @question.title %></h3>
		</div>
		<p class="qna-q-d"><%= @question.body %></p>
		<div class="qna-q-a">
			<%= render :partial => "questions/answer", :collection => @answers %>
		</div>
		<hr/>
		<%= render :partial => "answers/form" %>
	</div>
	<div class="span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<li class="nav-header">Asked by</li>
				<li><%= @question.user.email %></li>
				<li class="nav-header">Answered by</li>
				<%= render :partial => "questions/answerer", :collection => @answers %>
			</ul>
		</div>
	</div>
</div>